#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

required_files=(
  "README.md"
  "AGENTS.md"
  "upgrade-notes.md"
  "template-release.yaml"
  "docs/philosophy.md"
  "docs/core/workflow-summary.md"
  "docs/core/workflow-reference.md"
  "docs/core/glossary.md"
  "docs/core/operations.md"
  "docs/optional/consistency-gates.md"
  "docs/optional/specialist-tracks.md"
  "docs/optional/tiered-adoption.md"
  "docs/optional/concurrency-overlay.md"
  "docs/optional/deployment-patterns.md"
  "docs/optional/ideation-backlog.md"
  "docs/optional/decision-records.md"
  "docs/optional/full-irg-scoring.md"
  "docs/optional/task-queue.md"
  "docs/optional/quality-requirements.md"
  "docs/optional/traceability-matrix.md"
  "docs/optional/temp-measures.md"
  "docs/optional/task-dependencies.md"
  "docs/optional/feedback-matrix.md"
  "docs/optional/sign-off.md"
  "docs/optional/release-queue.md"
  "docs/optional/locks.md"
  "docs/optional/handoffs.md"
  "docs/guides/repo-modes.md"
  "docs/guides/template-sideloading.md"
  "docs/guides/worked-example.md"
  "0-ideation/README.md"
  "1-design/README.md"
  "1-design/PROJECT_BRIEF.md"
  "1-design/DESIGN_STATES.md"
  "1-design/TASK_READINESS.md"
  "1-design/ROADMAP.yaml"
  "1-design/archive/ROADMAP.yaml"
  "1-design/ROADMAP.md"
  "1-design/archive/ROADMAP.md"
  "2-build/README.md"
  "2-build/WORK_QUEUE.yaml"
  "2-build/archive/WORK_QUEUE.yaml"
  "2-build/WORK_QUEUE.md"
  "2-build/archive/WORK_QUEUE.md"
  "3-verify/README.md"
  "3-verify/TRACEABILITY_MATRIX.md"
  "4-sync/README.md"
  "meta/README.md"
  "meta/templates/README.md"
  "meta/templates/template-release-paths.txt"
  "1-design/templates/PROJECT_BRIEF_TEMPLATE.md"
  "2-build/templates/TASK_ENTRY_TEMPLATE.md"
  "0-ideation/templates/IDEA_ENTRY_TEMPLATE.md"
  "templates/component/COMPONENT_README_TEMPLATE.md"
  "templates/component/COMPONENT_AGENTS_TEMPLATE.md"
  "templates/init/workspace/WORKSPACE_README_TEMPLATE.md"
  "templates/init/workspace/WORKSPACE_AGENTS_TEMPLATE.md"
  "templates/init/workspace/WORKSPACE_README_FEDERATED_TEMPLATE.md"
  "templates/init/workspace/WORKSPACE_AGENTS_FEDERATED_TEMPLATE.md"
  "templates/sideload/WORKSPACE_TEMPLATE_STATE_TEMPLATE.yaml"
  "templates/sideload/WORKSPACE_TEMPLATE_LOCAL_OVERRIDES_TEMPLATE.md"
  "templates/agents/claude/CLAUDE_TEMPLATE.md"
  "templates/agents/claude/settings_TEMPLATE.json"
  "3-verify/templates/SECURITY_ANALYSIS_TEMPLATE.md"
  "3-verify/templates/EXPERIMENT_PLAN_TEMPLATE.md"
  "3-verify/templates/INCIDENT_RESPONSE_TEMPLATE.md"
  "scripts/package-template-release.sh"
  "1-design/FEATURE_REGISTRY.yaml"
  "1-design/DESIGN_STATES.yaml"
  "1-design/archive/DESIGN_STATES.yaml"
  "1-design/TASK_READINESS.yaml"
  "1-design/archive/TASK_READINESS.yaml"
  "3-verify/TRACEABILITY_MATRIX.yaml"
  "3-verify/FEEDBACK_MATRIX.yaml"
  "3-verify/archive/FEEDBACK_MATRIX.yaml"
  "3-verify/GAPS_AND_DEVIATIONS.yaml"
  "3-verify/archive/GAPS_AND_DEVIATIONS.yaml"
  "3-verify/acceptance-gate.md"
  "4-sync/DESIGN_INPUTS.yaml"
  "templates/init/0-ideation/INIT_IDEATION_BACKLOG_TEMPLATE.yaml"
  "templates/init/0-ideation/INIT_IDEATION_BACKLOG_DONE_TEMPLATE.yaml"
  "templates/init/4-sync/INIT_HANDOFFS_TEMPLATE.md"
  "templates/init/2-build/INIT_TEMP_MEASURES_TEMPLATE.yaml"
  "templates/init/2-build/INIT_TEMP_MEASURES_DONE_TEMPLATE.yaml"
  "templates/init/2-build/INIT_LOCKS_TEMPLATE.yaml"
  "templates/init/2-build/INIT_LOCKS_MD_TEMPLATE.md"
  "templates/init/2-build/INIT_TASK_DEPENDENCIES_TEMPLATE.yaml"
  "templates/init/2-build/INIT_TASK_DEPENDENCIES_MD_TEMPLATE.md"
  "templates/init/3-verify/INIT_SECURITY_REVIEWS_TEMPLATE.md"
  "templates/init/3-verify/INIT_EXPERIMENT_REVIEWS_TEMPLATE.md"
  "templates/init/3-verify/INIT_INCIDENT_RESPONSES_TEMPLATE.md"
)

missing=0
for file in "${required_files[@]}"; do
  if [[ ! -f "$REPO_ROOT/$file" ]]; then
    echo "MISSING: $file"
    missing=1
  fi
done

if [[ $missing -ne 0 ]]; then
  echo "Canonicality check failed." >&2
  exit 1
fi

echo "Canonicality check passed."
