#!/usr/bin/env bash
set -euo pipefail

# adapt-diff.sh — diff consumer files against a sideloaded bundle.
#
# Reads the adaptation contract from the bundle's template-release.yaml and:
#   - lists replace_reference_paths that would be refreshed from the bundle
#   - diffs adapt_in_place_paths between the consumer repo and the bundle
#
# Use the output as structured input for the local agent's adaptation pass
# so it works from a deterministic diff rather than an open-ended file scan.
#
# Usage (from repo root):
#   ./scripts/adapt-diff.sh <bundle-path>
#
# Example:
#   ./scripts/adapt-diff.sh .workspace-template-inbox/2026.04.01
# Or via make:
#   make adapt-diff BUNDLE=.workspace-template-inbox/2026.04.01

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUNDLE="${1:-}"

if [[ -z "$BUNDLE" ]]; then
  INBOX="$REPO_ROOT/.workspace-template-inbox"
  if [[ -d "$INBOX" ]]; then
    BUNDLE="$(ls -d "$INBOX"/*/ 2>/dev/null | sort -V | tail -1 || true)"
    BUNDLE="${BUNDLE%/}"
  fi
fi

if [[ -z "$BUNDLE" || ! -d "$BUNDLE" ]]; then
  echo "Usage: $0 <bundle-path>" >&2
  echo "  e.g. $0 .workspace-template-inbox/2026.04.01" >&2
  echo "" >&2
  echo "Or: make adapt-diff BUNDLE=.workspace-template-inbox/2026.04.01" >&2
  exit 1
fi

RELEASE_YAML="$BUNDLE/template-release.yaml"
if [[ ! -f "$RELEASE_YAML" ]]; then
  echo "ERROR: template-release.yaml not found in bundle at $BUNDLE" >&2
  exit 1
fi

echo "=== Sideload adaptation diff ==="
echo "Consumer: $REPO_ROOT"
echo "Bundle:   $BUNDLE"
echo ""

# ── YAML section reader ───────────────────────────────────────────────────────
# Reads a list under adaptation_contract.<section> from template-release.yaml.
# Handles indentation: contract at col 0, section at col 2, items at col 4.
read_contract_section() {
  local section="$1"
  local in_contract=0 in_section=0
  while IFS= read -r line; do
    [[ "$line" =~ ^adaptation_contract: ]] && { in_contract=1; continue; }
    if [[ "$in_contract" == 1 ]]; then
      [[ "$line" =~ ^[[:space:]]{2}"${section}": ]] && { in_section=1; continue; }
      if [[ "$in_section" == 1 ]]; then
        [[ "$line" =~ ^[[:space:]]{4}-[[:space:]](.+)$ ]] && { echo "${BASH_REMATCH[1]}"; continue; }
        [[ "$line" =~ ^[[:space:]]{2}[a-z] ]] && break
      fi
    fi
  done < "$RELEASE_YAML"
}

# ── Pattern expander ──────────────────────────────────────────────────────────
# Expands a contract pattern against a base directory.
# Supports exact paths and dir/** globs.
expand_in_dir() {
  local base="$1" pattern="$2"
  if [[ "$pattern" == *"/**" ]]; then
    local dir="${pattern%/**}"
    [[ -d "$base/$dir" ]] && find "$base/$dir" -type f | sort || true
  else
    [[ -f "$base/$pattern" ]] && echo "$base/$pattern" || true
  fi
}

# ── Replace-reference summary ─────────────────────────────────────────────────
echo "--- Files to replace from bundle ---"
echo ""
replace_count=0
while IFS= read -r pattern; do
  while IFS= read -r bundle_file; do
    rel="${bundle_file#"$BUNDLE/"}"
    if [[ -f "$REPO_ROOT/$rel" ]]; then
      echo "  replace  $rel"
    else
      echo "  new      $rel"
    fi
    (( replace_count++ )) || true
  done < <(expand_in_dir "$BUNDLE" "$pattern")
done < <(read_contract_section "replace_reference_paths")

[[ "$replace_count" -eq 0 ]] && echo "  (none found in bundle)"
echo ""

# ── Adapt-in-place diffs ──────────────────────────────────────────────────────
echo "--- Adapt-in-place diffs (consumer vs bundle) ---"
echo "(Skipping .yaml registers — handled by make migrate-plan)"
echo "(Skipping generated .md views — handled by make render)"
echo ""

diff_count=0
skip_count=0
while IFS= read -r pattern; do
  while IFS= read -r bundle_file; do
    rel="${bundle_file#"$BUNDLE/"}"

    # Skip .yaml register files — schema migrations are handled by make migrate-plan.
    if [[ "$bundle_file" == *.yaml ]]; then
      (( skip_count++ )) || true
      continue
    fi

    # Skip generated .md views — they start with the "Generated from" comment
    # and are regenerated by make render after migrations are applied.
    if [[ "$bundle_file" == *.md ]]; then
      first_line="$(head -1 "$bundle_file" 2>/dev/null || true)"
      if [[ "$first_line" == "<!-- Generated from"* ]]; then
        (( skip_count++ )) || true
        continue
      fi
    fi

    consumer_file="$REPO_ROOT/$rel"

    if [[ ! -f "$consumer_file" ]]; then
      echo "+++ NEW FILE: $rel (in bundle, not in consumer) +++"
      cat "$bundle_file"
      echo ""
      (( diff_count++ )) || true
      continue
    fi

    diff_out="$(diff --unified=3 "$consumer_file" "$bundle_file" || true)"
    if [[ -n "$diff_out" ]]; then
      echo "=== $rel ==="
      echo "$diff_out"
      echo ""
      (( diff_count++ )) || true
    fi
  done < <(expand_in_dir "$BUNDLE" "$pattern")
done < <(read_contract_section "adapt_in_place_paths")

if [[ "$diff_count" -eq 0 ]]; then
  echo "  No differences in adapt-in-place prose files — already in sync with the bundle."
fi
echo ""
echo "(Skipped $skip_count file(s) handled by migrate-plan or render)"
